config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  resources :questions

  resources :questions, only: [:index, :show, :edit, :update, :new, :destroy, :create] do
    resources :answers, only: [:index, :show, :new, :create]
  end

  root 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, length: { minimum: 50 }
  validates :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, length: { minimum: 40 }
  validates :description, length: { minimum: 150 }
end

app/controllers/answers_controller.rb
class AnswersController <ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)

    @question = Question.find(params[:question_id])
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Success!"
      redirect_to question_path(@question)

    else
      flash.now[:notice] = "Something went wrong."
      render 'questions/show'
    end
  end
  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


def index
  @questions = Question.order('created_at DESC')
end

def show
  @question = Question.find(params[:id])
  @answer = Answer.new
  @answers = Answer.order('created_at DESC')
end

def edit
  @question = Question.find(params[:id])

end

def destroy
  @question = Question.find(params[:id])

  @question.destroy

  redirect_to questions_path
end

def update
  @question = Question.find(params[:id])

  if @question.update(question_params)
    flash[:notice] = "You updated it, successfully!"
    redirect_to question_path(@question)
  else
    flash.now[:notice] = "It didn't work"
    render :edit
  end
end

def new
  @question = Question.new

end

def create
  @question = Question.new(question_params)

  if @question.save
    flash[:notice] = "Success!"
    redirect_to '/questions'
  else
    flash.now[:notice] = "Something went wrong."
    render :new
  end


end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash.any? %>
  <%= flash[:notice] %>
<% end %>
<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1><%= @question.title %></h1>
<%= button_to "delete", @question, :method => :delete %>
<%= form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
<% @questions.each do |question| %>
<li><%= link_to "#{question.title}", question_path(question) %><br><%= link_to "Edit", edit_question_path(question) %></li>
<% end %>


<li><a href='/questions/new'>New Question</a></li>
</ul>

<br>
<a href='/'>Home</a>

app/views/questions/new.html.erb
<h1>Questions</h1>

<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>
<br>
<a href='/'>Home</a><br>
<a href='/questions'>Questions Index</a>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<h3>Description:</h3>

<%= @question.description %>
<br>
<%= button_to "delete", @question, :method => :delete %>
<br>
<a href='/questions'>Back</a>

<h3>Answers:</h3>
<ul>
<% @question.answers.each do |answer| %>
<li><%= answer.description %></li>
<% end %>
</ul>

<%= form_for [@question, @answer] do |f| %>

  <% if @answer.errors.any? %>
    <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit 'Submit' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>


<a href='/questions'>Question Index</a><br>
<a href='/questions/new'>New Question</a>